#!/usr/bin/python3
# library to get arguments
import sys


def _factorial():
    """
    Factorize as many numbers as possible into a product of two smaller numbers.
    """
    try:
        current_file = sys.argv[1]
        with open(current_file) as t:
            for current_number in t:
                current_number = int(current_number)
                if current_number % 2 == 0:
                        print("{}={}*{}".format(current_number, current_number // 2, 2))
                        continue
                i = 3
                while i < current_number // 2:
                    if current_number % i == 0:
                        print("{}={}*{}".format(current_number, current_number // i, i))
                        break
                    i = i + 2
                if i == (current_number // 2) + 1:
                    print("{}={}*{}".format(current_number, current_number, 1))
    except (IndexError):
        pass


# automatically start the function
_factorial()
